begin;
do $$
declare j public.read_model_jobs; c public.read_model_jobs; reclaimed public.read_model_jobs; rejected boolean;
  summary jsonb := '{"groups":[{"supplier":"A"},{"supplier":"B"}]}';
begin
  j := public.request_read_model('ordering','batch-test','test-v1','{}');
  c := public.claim_read_model('{"ordering":"test-v1"}');
  if public.stage_ordering_read_model(j.id,gen_random_uuid(),'[]',true) then raise exception 'Wrong lease staged'; end if;
  perform public.stage_ordering_read_model(j.id,c.lease_token,'[{"supplier":"A","data":{"complete":true}}]',true);
  if (select status from public.read_model_jobs where id=j.id) <> 'running' then raise exception 'Partial rows became published'; end if;
  rejected := false;
  begin perform public.finish_ordering_read_model(j.id,c.lease_token,summary); exception when others then rejected:=true; end;
  if not rejected then raise exception 'Missing supplier published'; end if;
  perform public.stage_ordering_read_model(j.id,c.lease_token,'[{"supplier":"B","data":{"complete":true}}]');
  perform public.stage_ordering_read_model(j.id,c.lease_token,'[{"supplier":"B","data":{"complete":true}}]');
  rejected := false;
  begin perform public.finish_ordering_read_model(j.id,c.lease_token,'{"groups":[{"supplier":"A"},{"supplier":"C"}]}'); exception when others then rejected:=true; end;
  if not rejected then raise exception 'Mismatched supplier identities published'; end if;
  rejected := false;
  begin perform public.finish_ordering_read_model(j.id,c.lease_token,'{"groups":[{"supplier":"A"},{"supplier":"A"}]}'); exception when others then rejected:=true; end;
  if not rejected then raise exception 'Duplicate summary identities published'; end if;
  if not public.finish_ordering_read_model(j.id,c.lease_token,summary) then raise exception 'Complete snapshot not published'; end if;
  if (select count(*) from public.ordering_workspace_suppliers where snapshot_id=j.id) <> 2 then raise exception 'Batch retry duplicated rows'; end if;
  if public.stage_ordering_read_model(j.id,c.lease_token,'[]',true) then raise exception 'Completed snapshot modified'; end if;
  j := public.request_read_model('ordering','reclaim-test','test-v1','{}');
  c := public.claim_read_model('{"ordering":"test-v1"}');
  perform public.stage_ordering_read_model(j.id,c.lease_token,'[{"supplier":"abandoned","data":{}}]',true);
  update public.read_model_jobs set lease_until=now()-interval '1 second' where id=j.id;
  if public.stage_ordering_read_model(j.id,c.lease_token,'[]',true) then raise exception 'Expired lease staged'; end if;
  if public.finish_ordering_read_model(j.id,c.lease_token,summary) then raise exception 'Expired lease published'; end if;
  reclaimed := public.claim_read_model('{"ordering":"test-v1"}');
  perform public.stage_ordering_read_model(j.id,reclaimed.lease_token,'[{"supplier":"A","data":{}},{"supplier":"B","data":{}}]',true);
  if exists(select 1 from public.ordering_workspace_suppliers where snapshot_id=j.id and supplier='abandoned') then raise exception 'Reclaim retained stale rows'; end if;
  if public.finish_ordering_read_model(j.id,c.lease_token,summary) then raise exception 'Old lease published'; end if;
  update public.read_model_versions set version=version+1 where kind='ordering';
  if public.finish_ordering_read_model(j.id,reclaimed.lease_token,summary) then raise exception 'Obsolete snapshot published'; end if;
  if has_function_privilege('anon','public.stage_ordering_read_model(uuid,uuid,jsonb,boolean)','execute') then raise exception 'Anonymous stage allowed'; end if;
  if has_function_privilege('authenticated','public.finish_ordering_read_model(uuid,uuid,jsonb)','execute') then raise exception 'Browser publication allowed'; end if;
  if has_table_privilege('authenticated','public.ordering_workspace_suppliers','select') then raise exception 'Browser reads private staged rows'; end if;
end $$;
rollback;
